<Project>
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <Company>Awayra</Company>
    <Product>Awayra</Product>
    <Copyright>Copyright © Awayra</Copyright>
    <Version>1.0.3</Version>
    <FileVersion>1.0.3.0</FileVersion>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(MSBuildProjectName)' == 'Awayra.Core' or '$(MSBuildProjectName)' == 'Awayra.App'">
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
</Project>
